export const types = {
    FETCH_PARTNERS: 'FETCH_PARTNERS',
    UPDATE_PARTNER: 'UPDATE_PARTNER',
    FETCH_PARTNER: 'FETCH_PARTNER',
    FETCH_PARTNER_FROM_URL: 'FETCH_PARTNER_FROM_URL',
    RESET_CURRENT_PARTNER: 'RESET_CURRENT_PARTNER',
    CREATE_PARTNER: 'CREATE_PARTNER'
};