export const types = {
    FETCH_RESERVATIONS: 'FETCH_RESERVATIONS',
    FETCH_RESERVATION: 'FETCH_RESERVATION',
    DELETE_RESERVATION: 'DELETE_RESERVATION',
    UPDATE_RESERVATION: 'UPDATE_RESERVATION'
};