export const types = {
    FETCH_REVIEWS: 'FETCH_REVIEWS',
    FETCH_REVIEW: 'FETCH_REVIEW',
    DELETE_REVIEW: 'DELETE_REVIEW',
    UPDATE_REVIEW: 'UPDATE_REVIEW',
    CREATE_REVIEW: 'CREATE_REVIEW',

    SET_CURRENT_REVIEW: 'SET_CURRENT_REVIEW',
};